name: pyLCP
channels:
 - conda-forge
dependencies:
 - python=3.7
 - scipy
 - numpy
 - pandas
 - matplotlib
 - gdal=2.4
 - rasterio
 - geopandas
 - shapely
 - pip
 - psutil
 - scikit-image
 - ipython
 - jupyter
 - pip:
   - pyproj
